/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import de.codepitbull.rcon.Commands;
import de.codepitbull.rcon.RconConnection;

import java.net.URI;
import java.util.concurrent.ExecutionException;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        var con = new RconConnection(URI.create("tcp://127.0.0.1:27015"));
        con.connect();

        sendAndPrint(con, Commands.auth("iesaih3uY3esei3"));
        sendAndPrint(con, Commands.version());
        sendAndPrint(con, Commands.help());
        sendAndPrint(con, Commands.seed());
        sendAndPrint(con, Commands.cheat("game.player.cheat_mode=true"));
        sendAndPrint(con, Commands.cheat("game.player.force.research_all_technologies()"));
        sendAndPrint(con, Commands.cheat("for _, v in pairs(game.players) do game.local_player.print(v.name) end"));
        sendAndPrint(con, Commands.seed());
        sendAndPrint(con, Commands.find());

        con.disconnect();
    }

    public static void sendAndPrint(RconConnection con, Commands.RawCommand cmd) {
        System.out.println(cmd);
        try {
            System.out.println(con.send(cmd).get());
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        } catch (ExecutionException e) {
            throw new RuntimeException(e);
        }
    }

}
