/*
 * This source file was generated by the Gradle 'init' task
 */
package de.codepitbull.rcon;

import com.fasterxml.jackson.databind.ObjectMapper;
import de.codepitbull.rcon.factorio.Commands;
import de.codepitbull.rcon.proto.RconConnection;
import de.codepitbull.rcon.proto.Result;

import java.net.URI;
import java.util.List;

public class App {

    public static void main(String[] args) throws Exception {
        var con = new RconConnection(URI.create("tcp://127.0.0.1:27015"), "iesaih3uY3esei3");
        var conresult = con.connect();
        var mapper = new ObjectMapper();
        if (conresult instanceof Result.Failure) {
            System.exit(1);
        }

//        System.out.println(commands.cheat("game.player.cheat_mode=true").get());
//        System.out.println(commands.cheat("game.player.force.research_all_technologies()").get());
        System.out.println(Commands.find(mapper, con,"constant-combinator").get());

        System.out.println(Commands.readCombinatorSignal(mapper, con,List.of(new Commands.ReadSignalFromConstantCombinator(755, 23.5, -37.5, 1, "signal-A"))).get());
        System.out.println(Commands.setCombinatorSignal(mapper, con,List.of(new Commands.WriteSignalToConstantCombinator(755, 23.5, -37.5, 1, "signal-A", 1))).get());
        System.out.println(Commands.readCombinatorSignal(mapper, con,List.of(new Commands.ReadSignalFromConstantCombinator(755, 23.5, -37.5, 1, "signal-A"))).get());

        con.disconnect();
    }

}
